# Configurações específicas para produção (Railway)
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true

# Google Cloud
google:
  credentials:
    resource: ${GOOGLE_APPLICATION_CREDENTIALS_JSON}

# Firebase
firebase:
  credentials:
    resource: ${FIREBASE_APPLICATION_CREDENTIALS_JSON}
  storage:
    bucket: ${FIREBASE_BUCKET}
    project-id: ${FIREBASE_PROJECT_ID}


# Logging em produção
logging:
  level:
    root: INFO
    com.yagodaoud.venceja: INFO
    org.springframework.security: WARN
